const Types = {
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_RESPONSE: 'USER_LOGIN_RESPONSE',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  USER_LOGOUT_RESPONSE: 'USER_LOGOUT_RESPONSE',

  USER_SIGNUP_RESPONSE: 'USER_SIGNUP_RESPONSE',
  USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

  FETCH_USER_RESPONSE: 'FETCH_USER_RESPONSE',
};

export default Types;
